### ISSUE TITLE
AMIGOS site down?

### ISSUE THREAD

**Issue by creinemann** [happysat/Meteor-M-N-2-3-Satellite-Operational-Status#2]
Is the AMIGOS site down? http://185.26.115.106:8080/

**Comment by happysat** [comment]
Yes seems so, the server is hosted in russia, gonna ask!

**Comment by happysat** [comment]
Its not going back, so one can skip the lines in ini/ config.

**Comment by creinemann** [comment]
Ok thanks, that's a shame.

**Comment by creinemann** [comment]
Is happysat.nl down, or no longer in use? Getting some . lets say odd video on it...

**Comment by creinemann** [comment]
Site will not be reopening
